# Generated by Django 4.2.11 on 2025-04-02 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20230406_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalproject',
            name='institution',
            field=models.CharField(blank=True, max_length=10, default='None'),
        ),
        migrations.AddField(
            model_name='project',
            name='institution',
            field=models.CharField(blank=True, max_length=10, default='None'),
        ),
    ]
