# Generated by Django 4.2.11 on 2025-01-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_historicalproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalproject',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
