# Generated by Django 4.2.11 on 2025-01-12 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_historicalproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinstitutioncode',
            name='institution',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
