# Generated by Django 4.2.11 on 2025-01-10 23:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_alter_historicalproject_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcode',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
    ]
