# Generated by Django 4.2.11 on 2025-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectcode_project_projectinstitutioncode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinstitutioncode',
            name='institution',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
