# Generated by Django 4.2.11 on 2025-01-19 01:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projectcode_project_projectinstitutioncode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcode',
            name='institution',
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='project.project'),
        ),
        migrations.DeleteModel(
            name='ProjectInstitutionCode',
        ),
    ]
