# Generated by Django 4.2.11 on 2025-01-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projectinstitutioncode_institution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectinstitutioncode',
            name='institution',
            field=models.JSONField(default=list),
        ),
    ]
