# Generated by Django 4.2.11 on 2025-01-12 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_alter_projectinstitutioncode_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectcode',
            name='institution',
        ),
    ]
